### PR TITLE
Added guids as required to be able to bind video and audio sources

### PR DESCRIPTION
**Pull request by h1cks**
Ok, so I will be feeling a bit in the dark here.

When creating the render interfaces, I need a number of predefined GUIDs to identify source types.  At the moment, I my option would be to define these guid id's in code, or include these defines in Vortice.  

This may be an issue though, if we do pull these in, under the old sharpdx they were defined as static classes.  At the moment, alot of the interfaces are for a better word, type aware (they just accept the guid id, not a defined constant from a class).

Feel free to reject if need be, but I think maybe a wider discussion about media foundation implementation.  It is a bit like pulling on a thread at the moment.  I've raised a separate issue about build at the moment.  I can't seem to be able to build since I did my last merge from your master.

Update: @amerkoleci will work out the compile issues first, if you're ok with that, reject this pull request and I will resubmit.

i'm not tempted to bring in the mediaengine component as well.  But you may not be, let me know.

### CODE REVIEW

**Comment by amerkoleci** [comment]
CI builds are failing, can you fix before I merge?

**Comment by h1cks** [comment]
Issue seems to of been visual studio not allowing me to compile for some reason (usual weird VS issues).

Was able to fix the ifdef.  Do you have any issue if I add mediaengine back in also?

**Comment by h1cks** [comment]
build is compiling but is far from indication of success.  I've taken what seems to be a custom GUID class out of the code from the Sharpdx mappings and moved to System Guid.  Will need to review.

**Comment by amerkoleci** [comment]
Fix the CHANGELOG.md please and I'll merge

**Comment by h1cks** [comment]
That took a while all up.  I will need to do some more testing of the guids.   I will create a test project and work off the latest code.

**Pull request merged**
