### PR TITLE
Fix 'All' enum value in RegisterComponentMaskFlags

### PR DESCRIPTION
**Pull request by paulbartrum**

### CODE REVIEW

**Comment by amerkoleci** [comment]
Thanks!

**Comment by amerkoleci** [comment]
Curious, what are you working at using Vortice?

**Comment by amerkoleci** [comment]
Oh nice, using D3D11 or D3D12? I see you're using ImGui as well

**Comment by paulbartrum** [comment]
Yep! My current list of package dependencies: Vortice.Direct3D12, Vortice.Dxc, Vortice.XAudio2, Vortice.DirectStorage, Mochi.PhysX, ImGui.NET, K4os.Compression.LZ4, System.CommandLine.

**Comment by amerkoleci** [comment]
> K4os

Mochi.PhysX? How are the performance?

**Comment by paulbartrum** [comment]
> Mochi.PhysX? How are the performance?

Mochi.PhysX is a very low-level mapping (lots of pointers, etc) so performance is presumably good. (Though I haven't done any benchmarking to verify this.) I did try PhysX.Net first before switching to Mochi.PhysX, but I found PhysX.Net was missing some functionality. I think because PhysX.Net is using a hand-written mapping layer whereas Mochi.PhysX is using a tool to automate the C++ -> C# mapping.

**Comment by amerkoleci** [comment]
Nice, how are the performance of your game ? Compared to  native C++?

**Comment by paulbartrum** [comment]
> Nice, how are the performance of your game ? Compared to native C++?

I have no idea. I'm getting 400fps right now (1000fps with full-screen ambient occlusion turned off) so I can't really complain. My gut feeling is that .NET performance is easily good enough to make a commercial game in, as long as you avoid triggering the garbage collector during gameplay. Which with the prevalence of Span<T> is quite doable these days.

**Comment by amerkoleci** [comment]
You're targeting net6?

**Comment by paulbartrum** [comment]
.NET 7. I really like the 'required' keyword in C# 11.

**Pull request merged**
