### PR TITLE
Fix custom text renderer

### PR DESCRIPTION
**Pull request by manju-summoner**
First aid for #141 

I don't usually use the ref returns, so I'm not confident of this commit : https://github.com/amerkoleci/Vortice.Windows/commit/c60b0cd4d9106860479c43a292c53444a6eda89c

### CODE REVIEW

**Comment by andrew-boyarshin** [comment]
What are the differences compared to autogenerated code?

**Comment by manju-summoner** [comment]
Yes, SharpGen generate syntaxically incorrect code.

Copy Shadow from generated code, and Add IDWriteTextRenderer.cs with Shadow attribute : https://github.com/amerkoleci/Vortice.Windows/pull/144/commits/9cc065f10a0d41fc930ff9f992c14f3abdc1791f
Fix syntax error : https://github.com/amerkoleci/Vortice.Windows/pull/144/commits/c60b0cd4d9106860479c43a292c53444a6eda89c

If SharpGen will generate syntaxically correct code, use `<map interface="IDWriteTextRenderer\d*" callback="true" callback-dual="true" callback-visibility="public" autogen-shadow="true"/>` instead

**Comment by andrew-boyarshin** [comment]
I'll take care of fixing it in SharpGen (I think I already have in my local branch). In the mean time, if it fixes the issue, LGTM from me.

**Comment by amerkoleci** [comment]
Nice, thanks guys!

**Pull request merged**
