### PR TITLE
Fix Vortice.Dxc native library inclusion

### PR DESCRIPTION
**Pull request by Aminator**
The native DLLs should now always be copied next to the executable and if the platform is `AnyCPU` and no runtime identifier is specified, the `x64` versions of the libraries are copied. This works in UWP as well.

### CODE REVIEW

**Comment by amerkoleci** [comment]
Merged, please take note that I'm doing project renamed and some better code logic, it will be part of 1.1.0 release https://github.com/amerkoleci/Vortice.Windows/issues/14

**Comment by Sergio0694** [comment]
I've just upgraded to the `1.1.0` packages and unfortunately this PR seems to have broken .NET Core 3.0 support again 😟
I'm getting this exception:
image
This `Win32Exception` is the same one I used to get before `1.0.0`, when the needed .dlls were not loaded correctly be the application.

@Aminator Did you actually check whether your PR was working fine from .NET Core 3.0, when installing the package (locally) as NuGet package? I mean, not just when referencing the library as a project in the current solution.

**Comment by amerkoleci** [comment]
Hi @Sergio0694 ,
I just pushed new changes (https://github.com/amerkoleci/Vortice.Windows/commit/2e20a48d96575381351447f7b7de79adf6150a3d), now I'm using nativelibraryloader to load dxcompiler.

I saw that dxil.dll is not needed by dxcompiler.dll

**Comment by Aminator** [comment]
@amerkoleci It doesn't actually work with your changes, also you still need include `dxil.dll`, because it is needed when you create a pipeline state. The problem because mine didn't work was because when you reference the package implicitly, `ReferenceCopyLocalPaths` only copies it in the project it was directly referenced. I'm just going to submit a pull request again, where I just do a `Content` include instead and that works.

**Comment by Aminator** [comment]
@amerkoleci Ok, sorry, I was wrong, that ´NativeLibraryLoader´ actually solves all problems, we just need to load `dxil.dll` ourselves with the same method before creating a pipeline state. I doesn't make sense to load it in `Vortice.Dxc` as we may create a pipeline state without ever compiling (because we cached the shaders e.g.). So I don't think it's necessary to include it.

**Comment by amerkoleci** [comment]
Indeed, that one is https://github.com/mellinoe/nativelibraryloader

**Comment by amerkoleci** [comment]
The dxil.dll can be managed by other engines, I will release this fix with the 1.2.0 release at this point, sounds good?

**Comment by Aminator** [comment]
Yes

**Comment by amerkoleci** [comment]
Any change you can try dxr raytracing? So I can fix something else, my gpu doesn't support it

**Comment by Aminator** [comment]
I would love to try it, but I don't have a capable GPU as well. (Still waiting for the Surface Book 3.)

**Comment by Sergio0694** [comment]
@amerkoleci Hold on with `1.2.0` for a minute if you can, I'm in the middle of a PR 😄

**Comment by amerkoleci** [comment]
Yeah don't worry, will do the release Sunday probably, no rush :)

**Pull request merged**
