### PR TITLE
SharpGen 2.0.0-beta.10

### PR DESCRIPTION
**Pull request by andrew-boyarshin**
With fixes and improvements from SharpGenTools/SharpGenTools#200 and SharpGenTools/SharpGenTools#211. Checked to work with latest Avalonia master branch.

### CODE REVIEW

**Comment by amerkoleci** [comment]
Is Avalonia using vortice windows now?

**Comment by andrew-boyarshin** [comment]
No, but I still have a private branch that does.

**Comment by andrew-boyarshin** [comment]
Forgot to mention: now `ICallbackable` doesn't implement `IDisposable`, that means some changes are likely to be required to replace `using` declarations. Basically, the guidance is to use `try`/`finally` block and call `MemoryHelpers.Dispose` there. Sample change is present in `Vortice.Dxc` project in this PR.
Rationale: dropping `CallbackBase` inheritance requirement in the future.

**Review by h1cks — COMMENTED** [review]
For the IMFSourceRevolver changes, was it intended to revert the previous change?

**Comment by andrew-boyarshin** [comment]
@h1cks it's not a revert. I've simplified each pair of overloads into a single one using optional parameters. Ideally, this should be done across an entire `Vortice.Windows` project.

**Comment by h1cks** [comment]
Cheers. Just a query to ensure coverage on the merge.  No issues there. 

On a side note there seems to be a problem extracting values from a macro expansion.  Saw this in the dinput header.  The auto generated code was creating some weird casts o  the property guid in dinput. Not sure if human error on my part or the sharpgen cant handle it.  In the end i disabled the mapping and created by hand.  Maybe a good edge case to look at. Keep up the great work.

**Comment by andrew-boyarshin** [comment]
@h1cks it's more of a CastXML issue. It outputs `Expr` instead of a `EvaluatedStmt`/`APValue` for `Variable` GCCXML tags as init expression. When macro expands to something other than value and cast, that's an issue for SharpGen.

**Comment by h1cks** [comment]
@andrew-boyarshin thanks for that.  I was just wondering if I had been configuring things wrong.  But it sort of puts my mind at rest.  Because I did look at the intermediate files generated and I sort of guessed in my thoughts need another pass to then parse that expanded macro.  But not knowing how your tool works internally, im only theorising.  cheers for such an awesome tool btw.

**Pull request merged**
