### PR TITLE
DirectML: Additional fixes, derive array length.

### PR DESCRIPTION
**Pull request by Axiverse**

### CODE REVIEW

**Comment by amerkoleci** [comment]
Can you please cleanup commits, I see 18 commits but we actually care about only 2

**Comment by Axiverse** [comment]
> 

How do I go about doing this?

**Comment by amerkoleci** [comment]
You have to create branch and don't keep pushing on main branch

**Comment by Axiverse** [comment]
How would I migrate the new commits? I'd have to create another pull request?

Can we work from this for this pull request and I'll create another going forward?

**Pull request merged**
