### PR TITLE
Shader compiler tests

### PR DESCRIPTION
**Pull request by manuelxmarquez**
I often have issues when updating to a newer version of Vortice. Usually this is due to SharpGen, I have added some tests to help stabilize the project. The tests just compile some shaders.

Currently, the tests for Vortice.D3DCompiler are failing due to SharpGen.

### CODE REVIEW

**Comment by amerkoleci** [comment]
I will move tests under tests folder (like samples)

**Comment by amerkoleci** [comment]
@andrew-boyarshin Any thoughts why ShaderIncludeTest failes in Vortice.D3DCompiler.Test?

**Comment by andrew-boyarshin** [comment]
@amerkoleci simple: never define `Shadow` property unless you _really_ know what you're doing. `CallbackBase` implementation should be used 99.9% of the time.

**Comment by amerkoleci** [comment]
You mean this line:
https://github.com/amerkoleci/Vortice.Windows/blob/main/src/Vortice.DirectX/Mappings.xml#L268?

**Comment by andrew-boyarshin** [comment]
@amerkoleci no, I meant `Shadow` property in `ShaderIncludeHandler`.

**Comment by amerkoleci** [comment]
Thanks, fixed with commit: https://github.com/amerkoleci/Vortice.Windows/commit/278688ef4b57561dc7be68bee0b7a9687149c0e0

**Pull request merged**
