### PR TITLE
Fix NuGet packing of DXGI project

### PR DESCRIPTION
**Pull request by andrew-boyarshin**

### CODE REVIEW

**Comment by andrew-boyarshin** [comment]
The question remains: how did it work before?

**Comment by amerkoleci** [comment]
Wow that was fast, thanks!

**Comment by amerkoleci** [comment]
> The question remains: how did it work before?

Maybe some PR changed the solution file,  let me check

**Comment by andrew-boyarshin** [comment]
@amerkoleci no. It was a long time ago.

**Comment by amerkoleci** [comment]
Not sure then :) Probably latest .NET 6.0 broke the build, anyway it was issue with DirectInput project.

**Comment by andrew-boyarshin** [comment]
Investigation closed: dotnet/msbuild#4303
It was due to the introduction of multitargetting (`TargetFramework` -> `TargetFrameworks`).

**Pull request merged**
