### PR TITLE
Strong name signing, SourceLink support

### PR DESCRIPTION
**Pull request by andrew-boyarshin**
Note: Mathematics should be updated first.

### CODE REVIEW

**Comment by andrew-boyarshin** [comment]
This can be merged as is, but then strongly named assembly will depend on not strongly named one. It doesn't cause compilation issues (until someone depends on both strongly named and non-strongly-named version), but the result is still unsatisfactory. If you create Mathematics NuGet release and roll Mathematics version here, this will be a fully strongly named build.

**Comment by amerkoleci** [comment]
Okay, will do it now and update all.

Thanks

**Comment by andrew-boyarshin** [comment]
Once you create a release, I'll check that SourceLink is still working after disabling PDB embedding and pushing snupkg to NuGet instead and if it works, I'll update this PR with the new version number.

**Comment by andrew-boyarshin** [comment]
Yep. It has blown up.

**Comment by amerkoleci** [comment]
> Yep. It has blown up.

Indeed https://github.com/amerkoleci/Vortice.Mathematics/actions/runs/722181647

**Comment by andrew-boyarshin** [comment]
Feels like NuGet tried autopushing snupkg, and then my added snupkg push has caused the server error.

**Comment by andrew-boyarshin** [comment]
But `dotnet nuget push` has stopped autopushing snupkgs. Why did it try to do it now?

**Comment by amerkoleci** [comment]
> But `dotnet nuget push` has stopped autopushing snupkgs. Why did it try to do it now?
> 
> See [NuGet/Home#6113](https://github.com/NuGet/Home/issues/6113)

https://github.com/amerkoleci/Vortice.Windows/blob/main/.github/workflows/ci.yml#L51

**Comment by andrew-boyarshin** [comment]
I've explicitly updated the yml to push first nupkgs, then snupkgs: <https://github.com/amerkoleci/Vortice.Mathematics/commit/79a360e5ffaa50dfc60b9f85f43f30ab3a9b0f95#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR52>

**Comment by andrew-boyarshin** [comment]
It appears the package published successfully though.

**Comment by amerkoleci** [comment]
There seams to be:
https://www.nuget.org/packages/Vortice.Mathematics/1.3.18

**Comment by amerkoleci** [comment]
Its trying to push twice the  Vortice.Mathematics.1.3.18.snupkg

**Comment by andrew-boyarshin** [comment]
I've confirmed using NuGet Package Explorer that SourceLink info is present, points to valid `.cs` files, built assemblies are strongly named and NuGet Symbol Server has the necessary symbols.

**Comment by amerkoleci** [comment]
> I've confirmed using NuGet Package Explorer that SourceLink info is present, points to valid `.cs` files, built assemblies are strongly named and NuGet Symbol Server has the necessary symbols.

Okay, waiting for FIX on Vortice.Mathematics and update here then I'll merge everything.

**Comment by andrew-boyarshin** [comment]
Okay, now you're just kidding me. o_O
`The "Nerdbank.GitVersioning.Tasks.SetCloudBuildVariables" task failed unexpectedly. `

**Comment by amerkoleci** [comment]
> Okay, now you're just kidding me. o_O
> `The "Nerdbank.GitVersioning.Tasks.SetCloudBuildVariables" task failed unexpectedly. `

Just re-run the job, it happens :)

**Comment by amerkoleci** [comment]
Merged, lets see how it works :) I just released new stable release today, so we can expand with new stuff before new release.

**Pull request merged**
